build:
	if test "$(CMSSW_BASE)" == "" ; then cd CMSSW_*/src && cmsenv && cd -; fi
	make -C Kappa/DataFormats/test
	make -C KappaTools
	make -C Artus -j4
	make -C Excalibur
	
clean:
	make clean -C Kappa/DataFormats/test
	make clean -C KappaTools
	make clean -C Artus
	make clean -C Excalibur

check:
	make check -C Excalibur

help:
	make help -C Excalibur
